namespace Dnp3MasterTester.Models.Reports;

public sealed class ReportBrandingSettings
{
    public string CompanyName { get; set; } = "Commissioning Team";
    public string CustomerName { get; set; } = "Customer";
    public string ProjectName { get; set; } = "DNP3 Relay FAT";
    public string PreparedBy { get; set; } = Environment.UserName;
    public string ReviewedBy { get; set; } = string.Empty;
    public string ApprovedBy { get; set; } = string.Empty;
    public string FooterText { get; set; } = "Generated by DNP3 Master Tester";
    public string CompanyLogoPath { get; set; } = string.Empty;
    public string CustomerLogoPath { get; set; } = string.Empty;
}
